version: '3'
services: 
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile
        command: npm run start
        container_name: helloello
        ports:
            - "3000:3000"        
        volumes: 
            - ./:/helloello
            - /helloello/node_modules